micronaut:
  application:
    name: bootest
datasources:
  default:
    url: jdbc:mysql://localhost:3306/bootest
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    dialect: MYSQL
flyway:
  datasources:
    default:
      enabled: true